ARG PYTHON_VERSION={{python_version}}
ARG APP_HOME=/home/app

FROM python:${PYTHON_VERSION}-alpine AS builder
ARG PYTHON_VERSION
ARG APP_HOME

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

# UV_PROJECT_ENVIRONMENT has to match the path where it will be copied to in the runtime image. This is because it defines the interpreter path that will be used by gunicorn and supervisord. #!/home/app/venv/bin/python
RUN mkdir -p ${APP_HOME}
ENV UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1 \
    UV_PYTHON_DOWNLOADS=never \
    UV_PYTHON=python${PYTHON_VERSION} \
    UV_PROJECT_ENVIRONMENT=${APP_HOME}/venv

COPY django_proj/pyproject.toml /_lock/
COPY django_proj/uv.lock /_lock/

RUN <<EOT
cd /_lock
uv sync \
    --locked \
    --no-dev \
    --extra prod \
    --no-install-project \
    --no-editable
EOT

FROM python:${PYTHON_VERSION}-alpine AS runtime
ARG PYTHON_VERSION
ARG APP_HOME

# STOPSIGNAL SIGINT
RUN addgroup -S app && adduser -S app -G app

WORKDIR ${APP_HOME}
ENV PATH="${APP_HOME}/venv/bin:$PATH"

RUN apk update && \
    apk add bash nginx libgcc libpq
    
COPY --chown=app docker/.well-known/ .well-known/
COPY --chown=app --chmod=744 docker/docker-entrypoint.sh .
COPY --chown=app docker/supervisor.conf .
COPY docker/nginx_conf/default.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx_conf/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder --chown=app ${APP_HOME}/venv ./venv
COPY --chown=app django_proj/ .

USER app
RUN mkdir logs tmp

ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["supervisord", "-c", "supervisor.conf"]