ARG PYTHON_VERSION={{python_version}}
FROM jorgementx/pythonbuild:${PYTHON_VERSION}-alpine


RUN apk update && \
    apk add bash nginx libgcc libpq

{% if geodjango -%}
RUN apk add --no-cache geos gdal
{%- endif %}

COPY --chown=app docker/.well-known/ .well-known/
COPY --chown=app --chmod=744 docker/docker-entrypoint.sh .
COPY --chown=app docker/supervisor.conf .
COPY docker/nginx_conf/default.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx_conf/nginx.conf /etc/nginx/nginx.conf
COPY --chown=app django_proj/ .

RUN mkdir logs tmp

ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["supervisord", "-c", "supervisor.conf"]